---
- hosts: 172.16.66.10
#- hosts: hangli 
#- hosts: hangli_k8s
#- hosts: hangli_ceph
#  gather_facts: yes
  remote_user: root

  tasks:
  - name: Modify SSHD configuration
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin yes"

  - name: Restart SSHD service
    systemd:
      name: sshd
      state: restarted

