---
- hosts: 172.16.66.10
#- hosts: hangli 
#- hosts: hangli_k8s
#- hosts: hangli_ceph
#  gather_facts: yes
  remote_user: root
  vars_prompt:
    - name: new_password
      prompt: Input new password
      private: yes

  tasks:
  - name: Generate encrypt password
    command: openssl passwd -1 "{{new_password}}"
    register: crypted_password

  - name: Change root password
    user:
      name: root
      update_password: always
      #password: "{{ crypted_password.stdout | password_hash('sha512') }}"
      password: "{{ crypted_password.stdout }}"

