---
#- hosts: devops
#- hosts: bsi
- hosts: tai
#- hosts: cdh
  remote_user: root
  tasks:
  #- name: copy one file
  #  copy:
  #    src: /usr/bin/docker-compose
  #    dest: /usr/bin/
  #    mode: "0755"
  #    owner: root
  #    group: root

  - name: copy file
    copy:
      #src: files/netswatch.tar
      src: hosts
      #dest: /tmp/
      dest: /etc/hosts
      mode: "0744"
      owner: root
      group: root
 
  - name: Copy Aliyun pip conf
    copy:
      src: pip.conf
      dest: ~/.pip
    tags: ["pipconf"]

  - name: Copy filebeat conf
    copy:
      src: custom_filebeat.yml
      dest: /deploy/filebeat/custom_filebeat.yml
    tags: ["filebeat"]

  - name: Copy swarm-port.py
    copy:
      src: swarm-port.py
      dest: /tmp/swarm-port.py
    tags: ["swarm"]

