---
#- hosts: hangli
- hosts: devops
#- hosts: noreg
  remote_user: root

  vars:
    netdata_dir: /opt/devops/netdata

  tasks:
  - name: Upload configuration
    copy:
      src: files/netdata/
      dest: /opt/devops/netdata
      mode: "0755"
      owner: root
      group: root
    tags: ["upload"]

  - name: Replace line
    lineinfile:
      path: "{{netdata_dir}}/docker-compose.yml"
      regexp: 'restart.*'
      line: "    restart: always"
    tags: ["never"]

  - name: Restart Netdata
    shell: "docker-compose -p netdata -f {{netdata_dir}}/docker-compose.yml up -d"
    tags: ["up"]

  - name: Stop Netdata
    shell: "docker-compose -p netdata -f {{netdata_dir}}/docker-compose.yml down"
    tags: ["down"]

