---
#- hosts: hangli
#- hosts: telecom
- hosts: netswatch
#- hosts: bsi
#- hosts: noreg
  remote_user: root

  vars:
    netswatch_dir: /opt/devops/netswatchgo
    netswatch_proj: netswatchgo
    image_version: 1.0.7

  tasks:
  - name: Upload image
    copy:
      src: files/netswatch.tar
      dest: /tmp/
      mode: "0755"
      owner: root
      group: root
    tags: ["upload"]

  - name: Load image
    shell:
      cmd: docker load < /tmp/netswatch.tar
    tags: ["load"]

  - name: Replace ENV
    replace:
      path: "{{netswatch_dir}}/docker-compose.yml"
      regexp: 'NW_LOOP=.*'
      replace: "NW_LOOP=600"
    tags: ["never"]

  - name: Add ENV
    lineinfile:
      path: "{{netswatch_dir}}/docker-compose.yml"
      insertafter: 'NW_LOOP=.*'
      line: "      - NW_SUBNET_LEASE_TTL=7200 "
    tags: ["add"]


  - name: Update image tag
    replace:
      path: "{{netswatch_dir}}/docker-compose.yml"
      regexp: '(.*image.*/)netswatch:.*'
      replace: '\1netswatch:{{image_version}}'
    tags: ["tag"]

  - name: Netswatch up
    shell: "docker-compose -p {{netswatch_proj}} -f {{netswatch_dir}}/docker-compose.yml up -d"
    tags: ["up"]

  - name: Netswatch down
    shell: "docker-compose -p {{netswatch_proj}} -f {{netswatch_dir}}/docker-compose.yml down"
    tags: ["down"]

  - name: Restart Netswatch
    shell: "docker-compose -p {{netswatch_proj}} -f {{netswatch_dir}}/docker-compose.yml restart"
    tags: ["restart"]
