# Setup for Centos
---
- name: Install Basic Packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - lrzsz
    - iputils
    - telnet
    - net-tools
    - sysstat
    - vim
  tags: basic

- name: DEBUG
  debug:
    msg: "{{ USE_ALI_REPO }}"
  when: USE_ALI_REPO
  tags: repo

- name: Disable Firewall (CentOS 7)
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution_major_version == "7"

- name: Disable Firewall (CentOS 6)
  service:
    name: iptables
    state: stopped
    enabled: no
  when: ansible_distribution_major_version == "6"

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable SSH DNS
  replace:
    path: /etc/ssh/sshd_config
    regexp: '.*UseDNS.+'
    replace: 'UseDNS no'
    backup: yes

- name: Restart SSHD
  service:
    name: sshd
    state: restarted

