# This role will do initialization job on Linux distributions
# Test on Ubuntu 16.04 and CentOS 7.6
---
- include: "{{ ansible_distribution | lower }}-setup.yaml"
  tags: ['basic', 'ntp', 'repo']

- include_tasks: banner-setup.yaml 
  when: banner is defined

- name: Configure Hostname
  hostname:
    name: "{{ host_name }}"
  when: host_name is defined
  tags: ['hostname']

#- name: Modify ulimit soft
#  pam_limits:
#    domain: root
#    limit_type: soft
#    limit_item: nofile
#    value: 65535
#
#- name: Modify ulimit hard
#  pam_limits:
#    domain: root
#    limit_type: hard
#    limit_item: nofile
#    value: 655350
