# Setup for Ubuntu
---
- name: Copy Ali repo
  copy:
    src: "repo/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: USE_ALI_REPO
  tags: repo

- name: Update Ali cache
  apt:
    update_cache: yes
  when: USE_ALI_REPO
  tags: repo

- name: Install Basic Packages
  apt:
    name: "{{ packages }}"
    install_recommends: no
    state: present
  vars:
    packages:
    - lrzsz
    - iputils-ping
    - telnet
    - net-tools
    - sysstat
    - vim
    - ntp
  tags: basic
